USE master;
GO

CREATE DATABASE DB_VENDAS
ON
(
	NAME = DB_VENDAS_DAT,
	FILENAME= N'C:\Users\Ta0505\Documents\Sinqia_AspNet\Data\DbEventos.mdf',
	SIZE = 5000KB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=1000KB
)
LOG ON 
(
	NAME = DB_VENDAS_LOG,
	FILENAME= N'C:\Users\Ta0505\Documents\Sinqia_AspNet\Data\DbEventos_log.ldf',
	SIZE = 2000KB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=1000KB
);
GO